# Generated by Django 3.0 on 2024-08-27 08:55

from django.db import migrations


def copy_address_letting_data(apps, schema_editor):
    old_address = apps.get_model('oc_lettings_site', 'Address')
    old_letting = apps.get_model('oc_lettings_site', 'Letting')
    new_address = apps.get_model('lettings', 'Address')
    new_letting = apps.get_model('lettings', 'Letting')

    for old_address in old_address.objects.all():
        new_address.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )

    for old_letting in old_letting.objects.all():
        new_letting.objects.create(
            title=old_letting.title,
            address=new_address.objects.get(pk=old_letting.address.pk)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_address_letting_data),
    ]
